name: Update JSON on OpenAPI Spec Change

on:
  push:
    paths:
      - openapispec/unified/XI-Resellers-API-Spec.yaml
  workflow_dispatch: 

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts'

    - name: Install dependencies
      run: npm install js-yaml

    - name: Convert OpenAPI YAML to JSON
      run: |
        node -e "
        const fs = require('fs');
        const yaml = require('js-yaml');
        const yamlContent = fs.readFileSync('openapispec/unified/XI-Resellers-API-Spec.yaml', 'utf8');
        const jsonContent = JSON.stringify(yaml.load(yamlContent), null, 2);
        fs.writeFileSync('openapispec/unified/XI-Resellers-API-Spec.json', jsonContent);
        "

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name ${{secrets.ORG_NAME}}
        git config --global user.email ${{secrets.ADMIN_EMAIL}}
        git pull --rebase origin $(git rev-parse --abbrev-ref HEAD)
        git add openapispec/unified/XI-Resellers-API-Spec.json
        git commit -m 'Update JSON file based on OpenAPI spec changes' || echo "No changes to commit"
        git push origin $(git rev-parse --abbrev-ref HEAD)
